-- MySQL Script generated by MySQL Workbench
-- Wed Oct  8 14:10:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SUCURSAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUCURSAL` (
  `codigo` INT NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADOS` (
  `NIF` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `SUCURSAL_codigo` INT NOT NULL,
  PRIMARY KEY (`NIF`),
  INDEX `fk_EMPLEADOS_SUCURSAL_idx` (`SUCURSAL_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADOS_SUCURSAL`
    FOREIGN KEY (`SUCURSAL_codigo`)
    REFERENCES `mydb`.`SUCURSAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REVISTA` (
  `num_registro` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `periodicidad` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_registro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERIODISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERIODISTAS` (
  `NIF` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NULL,
  `PERIODISTAScol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SECCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SECCIONES` (
  `titulo` INT NOT NULL,
  `extensión` VARCHAR(45) NOT NULL,
  `REVISTA_num_registro` INT NOT NULL,
  INDEX `fk_SECCIONES_REVISTA1_idx` (`REVISTA_num_registro` ASC) VISIBLE,
  CONSTRAINT `fk_SECCIONES_REVISTA1`
    FOREIGN KEY (`REVISTA_num_registro`)
    REFERENCES `mydb`.`REVISTA` (`num_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EJEMPLAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EJEMPLAR` (
  `fecha` INT NOT NULL,
  `nºpaginas` VARCHAR(45) NOT NULL,
  `nºejemplares vendidos` VARCHAR(45) NOT NULL,
  `REVISTA_num_registro` INT NOT NULL,
  INDEX `fk_EJEMPLAR_REVISTA1_idx` (`REVISTA_num_registro` ASC) VISIBLE,
  CONSTRAINT `fk_EJEMPLAR_REVISTA1`
    FOREIGN KEY (`REVISTA_num_registro`)
    REFERENCES `mydb`.`REVISTA` (`num_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUCURSAL_has_REVISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUCURSAL_has_REVISTA` (
  `SUCURSAL_codigo` INT NOT NULL,
  `REVISTA_num_registro` INT NOT NULL,
  PRIMARY KEY (`SUCURSAL_codigo`, `REVISTA_num_registro`),
  INDEX `fk_SUCURSAL_has_REVISTA_REVISTA1_idx` (`REVISTA_num_registro` ASC) VISIBLE,
  INDEX `fk_SUCURSAL_has_REVISTA_SUCURSAL1_idx` (`SUCURSAL_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_SUCURSAL_has_REVISTA_SUCURSAL1`
    FOREIGN KEY (`SUCURSAL_codigo`)
    REFERENCES `mydb`.`SUCURSAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUCURSAL_has_REVISTA_REVISTA1`
    FOREIGN KEY (`REVISTA_num_registro`)
    REFERENCES `mydb`.`REVISTA` (`num_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVISTA_has_PERIODISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REVISTA_has_PERIODISTAS` (
  `REVISTA_num_registro` INT NOT NULL,
  `PERIODISTAS_NIF` INT NOT NULL,
  PRIMARY KEY (`REVISTA_num_registro`, `PERIODISTAS_NIF`),
  INDEX `fk_REVISTA_has_PERIODISTAS_PERIODISTAS1_idx` (`PERIODISTAS_NIF` ASC) VISIBLE,
  INDEX `fk_REVISTA_has_PERIODISTAS_REVISTA1_idx` (`REVISTA_num_registro` ASC) VISIBLE,
  CONSTRAINT `fk_REVISTA_has_PERIODISTAS_REVISTA1`
    FOREIGN KEY (`REVISTA_num_registro`)
    REFERENCES `mydb`.`REVISTA` (`num_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVISTA_has_PERIODISTAS_PERIODISTAS1`
    FOREIGN KEY (`PERIODISTAS_NIF`)
    REFERENCES `mydb`.`PERIODISTAS` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
