-- MySQL Script generated by MySQL Workbench
-- Mon Feb 16 08:42:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADOS` (
  `nombre` INT NOT NULL,
  `fecha_nac` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NOT NULL,
  `EMPLEADOS_nombre` INT NOT NULL,
  `EMPLEADOS_dni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`, `dni`),
  INDEX `fk_EMPLEADOS_EMPLEADOS1_idx` (`EMPLEADOS_nombre` ASC, `EMPLEADOS_dni` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADOS_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_nombre` , `EMPLEADOS_dni`)
    REFERENCES `mydb`.`EMPLEADOS` (`nombre` , `dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MESA` (
  `nºmesa` INT NOT NULL,
  `tamaño` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  PRIMARY KEY (`nºmesa`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `id_pedido` INT NOT NULL,
  `Cantidad` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `EMPLEADOS_nombre` INT NOT NULL,
  `EMPLEADOS_dni` VARCHAR(45) NOT NULL,
  `MESA_nºmesa` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDO_EMPLEADOS1_idx` (`EMPLEADOS_nombre` ASC, `EMPLEADOS_dni` ASC) VISIBLE,
  INDEX `fk_PEDIDO_MESA1_idx` (`MESA_nºmesa` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_nombre` , `EMPLEADOS_dni`)
    REFERENCES `mydb`.`EMPLEADOS` (`nombre` , `dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_MESA1`
    FOREIGN KEY (`MESA_nºmesa`)
    REFERENCES `mydb`.`MESA` (`nºmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGO` (
  `fecha` INT NULL,
  `hora` VARCHAR(45) NULL,
  `importe` VARCHAR(45) NULL,
  `id_pago` VARCHAR(45) NOT NULL,
  `PEDIDO_id_pedido` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_PAGO_PEDIDO1_idx` (`PEDIDO_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PAGO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `mydb`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA` (
  `nombre_reserva` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `id_reserva` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `nombre` INT NOT NULL,
  `precio` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INGREDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INGREDIENTE` (
  `nombre` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROVEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVEDOR` (
  `nombre` INT NOT NULL,
  `contacto` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_has_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_has_PEDIDO` (
  `PRODUCTO_nombre` INT NOT NULL,
  `PEDIDO_id_pedido` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCTO_nombre`, `PEDIDO_id_pedido`),
  INDEX `fk_PRODUCTO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_id_pedido` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_nombre`)
    REFERENCES `mydb`.`PRODUCTO` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `mydb`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_has_INGREDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_has_INGREDIENTE` (
  `PRODUCTO_nombre` INT NOT NULL,
  `INGREDIENTE_nombre` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_nombre`, `INGREDIENTE_nombre`),
  INDEX `fk_PRODUCTO_has_INGREDIENTE_INGREDIENTE1_idx` (`INGREDIENTE_nombre` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_INGREDIENTE_PRODUCTO1_idx` (`PRODUCTO_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_INGREDIENTE_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_nombre`)
    REFERENCES `mydb`.`PRODUCTO` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_INGREDIENTE_INGREDIENTE1`
    FOREIGN KEY (`INGREDIENTE_nombre`)
    REFERENCES `mydb`.`INGREDIENTE` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INGREDIENTE_has_PROVEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INGREDIENTE_has_PROVEDOR` (
  `INGREDIENTE_nombre` INT NOT NULL,
  `PROVEDOR_nombre` INT NOT NULL,
  PRIMARY KEY (`INGREDIENTE_nombre`, `PROVEDOR_nombre`),
  INDEX `fk_INGREDIENTE_has_PROVEDOR_PROVEDOR1_idx` (`PROVEDOR_nombre` ASC) VISIBLE,
  INDEX `fk_INGREDIENTE_has_PROVEDOR_INGREDIENTE1_idx` (`INGREDIENTE_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_INGREDIENTE_has_PROVEDOR_INGREDIENTE1`
    FOREIGN KEY (`INGREDIENTE_nombre`)
    REFERENCES `mydb`.`INGREDIENTE` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INGREDIENTE_has_PROVEDOR_PROVEDOR1`
    FOREIGN KEY (`PROVEDOR_nombre`)
    REFERENCES `mydb`.`PROVEDOR` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MESA_has_RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MESA_has_RESERVA` (
  `MESA_nºmesa` INT NOT NULL,
  `RESERVA_id_reserva` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MESA_nºmesa`, `RESERVA_id_reserva`),
  INDEX `fk_MESA_has_RESERVA_RESERVA1_idx` (`RESERVA_id_reserva` ASC) VISIBLE,
  INDEX `fk_MESA_has_RESERVA_MESA1_idx` (`MESA_nºmesa` ASC) VISIBLE,
  CONSTRAINT `fk_MESA_has_RESERVA_MESA1`
    FOREIGN KEY (`MESA_nºmesa`)
    REFERENCES `mydb`.`MESA` (`nºmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESA_has_RESERVA_RESERVA1`
    FOREIGN KEY (`RESERVA_id_reserva`)
    REFERENCES `mydb`.`RESERVA` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
