<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.rafael</groupId>
    <artifactId>ejercicio1-videojuegos</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
	 <dependency>
	    <groupId>mysql</groupId>
	    <artifactId>mysql-connector-java</artifactId>
	    <version>8.0.33</version>
	</dependency>
	<!-- Jackson Core -->
 <dependency>
 <groupId>com.fasterxml.jackson.core</groupId>
 <artifactId>jackson-core</artifactId> 
 <version>2.13.3</version>
 </dependency>
 <!-- Jackson Databind -->
 <dependency>
 <groupId>com.fasterxml.jackson.core</groupId>
 <artifactId>jackson-databind</artifactId>
 <version>2.13.3</version>
 </dependency>
 <!-- Jackson XML Dataformat -->
 <dependency>
 <groupId>com.fasterxml.jackson.dataformat</groupId>
 <artifactId>jackson-dataformat-xml</artifactId>
 <version>2.13.3</version>
 </dependency>
</dependencies>

</project>